# Generated by Django 3.2.12 on 2024-12-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0011_train_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('declined', 'Declined')], default='Pending', max_length=100),
        ),
    ]
