# Generated by Django 3.2.12 on 2024-12-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0012_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MerchantRequestId', models.CharField(max_length=100, unique=True)),
                ('CheckoutRequestId', models.CharField(max_length=100)),
                ('ResponseCode', models.CharField(max_length=100)),
                ('ResponseDescription', models.TextField()),
                ('CustomerMessage', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Approved', 'approved'), ('Declined', 'declined')], default='Pending', max_length=100),
        ),
    ]
