# Generated by Django 3.2.12 on 2024-12-13 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0014_auto_20241212_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='booking_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='train.booking'),
        ),
    ]
